name: Publish to GitHub registry

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: '@kaiosilveira'

      - name: Force npm version
        run: npm install -g npm@9.6.7

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run prettier:check

      - name: Check code style
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Publish to GitHub registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
